# Generated by Django 4.1.5 on 2023-03-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('date', 'employee'), name='unique_employee_work_date', violation_error_message='Employee already has a shift                    scheduled for that day!'),
        ),
    ]
