# Generated by Django 4.1.5 on 2023-03-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_schedule_unique_employee_work_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_employee_work_date',
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('date', 'employee'), name='unique_employee_work_date', violation_error_message='Employee already has a shiftscheduled for that day!'),
        ),
    ]
