# Generated by Django 4.1.5 on 2023-03-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='took_place',
            field=models.BooleanField(null=True),
        ),
    ]
