# Generated by Django 4.1.5 on 2023-02-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='personal_id',
            field=models.CharField(default='12345678911', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
